#!/usr/bin/env bash
# installs nginx and configures it on a remote server

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx
cat <<EOF >/etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    add_header X-Served-By \$hostname;


    location / {
           try_files $uri $uri/ =404;

    }
}
EOF

# Restart Nginx
kill -s HUP $(cat /var/run/nginx.pid)

